### ISSUE TITLE
err-stackstorm fails to install when STACKSTORM configuration is missing

### ISSUE THREAD

**Issue by nzlosh** [nzlosh/err-stackstorm#11]
If the `STACKSTORM` configuration is missing or invalid in errbot's `config.py` it causes an exception to be raised.

Raised exceptions prevent the plugin from being installed.  Update documentation to warn about this and attempt to refactor the code so that missing configuration is gracefully handled.

Thanks to @spudpnds on StackStorm community slack for reporting this issue.

**Comment by spudlyo** [comment]
Here is an example when the config is missing entirely:
```
Traceback (most recent call last):
  File "/home/spud/python/errbot/lib/python3.4/site-packages/yapsy/PluginManager.py", line 538, in loadPlugins
    plugin_info.plugin_object = self.instanciateElementWithImportInfo(element, element_name, plugin_module_name, candidate_filepath)
  File "/home/spud/python/errbot/lib/python3.4/site-packages/yapsy/PluginManager.py", line 587, in instanciateElementWithImportInfo
    return self.instanciateElement(element)
  File "/home/spud/python/errbot/lib/python3.4/site-packages/errbot/plugin_manager.py", line 265, in instanciateElement
    return element(self.bot, name=self._current_pluginfo.name)
  File "/home/spud/python/errbot/data/plugins/nzlosh/err-stackstorm/st2.py", line 34, in __init__
    self.cfg.setup(self.bot_config, PLUGIN_PREFIX)
  File "/home/spud/python/errbot/data/plugins/nzlosh/err-stackstorm/lib/config.py", line 29, in setup
    self._configure_credentials(bot_conf)
  File "/home/spud/python/errbot/data/plugins/nzlosh/err-stackstorm/lib/config.py", line 65, in _configure_credentials
    self.api_auth = bot_conf.STACKSTORM.get("api_auth", {})
```

**Comment by nzlosh** [comment]
The configuration code now catches missing `STACKSTORM` configuration and attempts to provide reasonable default values.  Any exceptions are logged but not raised.

A installation of the plugin without any `STACKSTORM` configuration succeeded.
```
Installing https://github.com/nzlosh/err-stackstorm.git...
A new plugin repository has been installed correctly from https://github.com/nzlosh/err-stackstorm.git. Refreshing the plugins commands...
Plugins reloaded.
```
