### ISSUE TITLE
Unable to install err-stackstorm for errbot

### ISSUE THREAD

**Issue by trungatdoshii** [nzlosh/err-stackstorm#46]
Error received:
```
2022-10-26 10:44:08,585 ERROR    errbot.bootstrap          Some plugins failed to load:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/errbot/plugin_manager.py", line 289, in _load_plugins_generic
    plugin_classes = plugin_info.load_plugin_classes(
  File "/usr/local/lib/python3.9/site-packages/errbot/plugin_info.py", line 100, in load_plugin_classes
    spec.loader.exec_module(modu1e)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/errbot/data/plugins/nzlosh/err-stackstorm/st2.py", line 11, in <module>
    from lib.config import PluginConfiguration
ModuleNotFoundError: No module named 'lib.config'; 'lib' is not a package
```

this is after installing using `!repos install <reponame>`

**Comment by nzlosh** [comment]
Thank you for raising this issue.  I'll try and replicate and get back to you.

**Comment by nzlosh** [comment]
I was able to reproduce the error.  Errbot recently got a new feature allowing it to install plugins and backends via pip.  This is a much nicer method for installation process than git clone but did bring some changes with how python search paths were handled.

I've update err-stackstorm to use source layout so it can be packaged on pypi or installed via git clone.

**Comment by nzlosh** [comment]
Are you able to confirm the new layout has resolved the error during installation?

**Comment by trungatdoshii** [comment]
Hi there! Thanks for getting on this promptly!
The installation works fine, but I'm getting this: 
```
Installing https://github.com/nzlosh/err-stackstorm.git...
A new plugin repository has been installed correctly from https://github.com/nzlosh/err-stackstorm.git. Refreshing the plugins commands...
Error: St2 failed to activate: 'NoneType' object has no attribute 'is_activated'.
```

Any ideas? I can open a separate issue if required.

This is my config:
```py3
# the below is the docker network bridge
# currently running stackstorm on docker for testing (127.0.0.1)
ST2_HOST = '192.168.65.1'

STACKSTORM = {
    'auth_url': 'http://{}/auth/v1'.format(ST2_HOST),
    'api_url': 'http://{}/auth/v1'.format(ST2_HOST),
    'stream_url': 'http://{}/auth/v1'.format(ST2_HOST),
    'route_key': 'errbot',
    'plugin_prefix': 'st2',
    'verify_cert': False,
    'secrets_store': 'cleartext',
    'api_auth': {
        'apikey': '<keyvalue>'
    },
    'rbac_auth': {
        'standalone': {},
    },
    'timer_update': 900, #  Unit: second.  Interval to check the user token is still valid.
}

```

**Comment by nzlosh** [comment]
Yes, that's a separate issue.  You should check errbot's logs for error messages.
