### ISSUE TITLE
SyntaxError: invalid syntax - typo in file enquiry.py

### ISSUE THREAD

**Issue by greenfox878** [nzlosh/err-stackstorm#48]
Fresh installation on ubuntu 18 with lates updates
```
[@CHANGE_ME ➡ @errbot] >>> !repos install https://github.com/nzlosh/err-stackstorm.git
Installing https://github.com/nzlosh/err-stackstorm.git...
Enumerating objects: 1547, done.
Counting objects: 100% (297/297), done.
Compressing objects: 100% (106/106), done.
Total 1547 (delta 205), reused 233 (delta 179), pack-reused 1250
copied 1546 pack entries46/1547
Some plugins are generating errors:
Traceback (most recent call last):
  File "/opt/errbot/.venv/lib/python3.8/site-packages/errbot/plugin_manager.py", line 289, in _load_plugins_generic
    plugin_classes = plugin_info.load_plugin_classes(
  File "/opt/errbot/.venv/lib/python3.8/site-packages/errbot/plugin_info.py", line 100, in load_plugin_classes
    spec.loader.exec_module(modu1e)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/errbot/data/plugins/nzlosh/err-stackstorm/src/err-stackstorm/st2.py", line 17, in <module>
    from errst2lib.enquiry import Enquiry, EnquiryManager
  File "/opt/errbot/data/plugins/nzlosh/err-stackstorm/src/err-stackstorm/errst2lib/enquiry.py", line 84
    def get_associated_data(cls)
                               ^
SyntaxError: invalid syntax
.
Removing /opt/errbot/data/plugins/nzlosh/err-stackstorm as it did not load correctly.
Error: St2 failed to activate: 'NoneType' object has no attribute 'is_activated'.
Error: WebserverConfiguration failed to activate: WebserverConfiguration failed to start : Invalid state, you should not have a webserver already running...
Plugins reloaded.
```

**Comment by nzlosh** [comment]
Thanks, it's fixed.
